const EstimatesActionTypes = {
    GET_ESTIMATES_SUCCESS: 'GET_ESTIMATES_SUCCESS',
    GET_ESTIMATES_FAILURE: 'GET_ESTIMATES_FAILURE',
    CHECK_ESTIMATES: 'CHECK_ESTIMATES'

}
export default EstimatesActionTypes